apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-agile-health-care-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: star-agile-health-care
  template:
    metadata:
      labels:
        app: star-agile-health-care
    spec:
      containers:
      - name: star-agile-health-care
        image: subkamble/star-agile-health-care:latest
        ports:
        - containerPort: 8082
